### ISSUE TITLE
Support both gitignore and minimatch ignore type

### ISSUE THREAD

**Issue by pvdlg** [kaelzhang/node-glob-gitignore#1]
It seems this library replace the `node-glob` `ignore` option with one that is compatible with the `.gitignore` format, but we loose the ability to use regular `minimatch` ignore.

Would it be possible to have instead the options:
- `ignore`: works like the regular `node-glob` `ignore` options
- `gitignore`: works with `gitignore` format

That would to support cases in which we have both a `.gitignore` file and `minimatch` pattern to ignore.

**Comment by kaelzhang** [comment]
Maybe [`globby`](https://www.npmjs.com/package/globby) is a good choice which also depends on [`node-ignore`](https://github.com/kaelzhang/node-ignore) now

**Comment by kaelzhang** [comment]
I'd be thinking to deprecate this module for globby supports .gitignore in the latest version.

**Comment by pvdlg** [comment]
Well actually I was looking at `node-glob-gitignore` as a way to improve the performances of `globby`.

Currently `globby` uses `node-glob` to retrieve all the files, and use the regular `ignore` options and then filter them with with the exclusion of the `.gitignore`.

Performances could maybe be improved by doing all that at once (like avoid to retrieve files to filter them after)

**Comment by kaelzhang** [comment]
Yep, that is the only reason to use `glob-gitignore` for now.

That is a good question. Let me explain that.

But actually, the behavior of gitignore is differrent from and even conflicting with `minimatch`, especially for negative patterns (rules). 

> It is not possible to re-include a file if a parent directory of that file is excluded.

while `minimatch` is only a pattern but not a rule definition for group of patterns, and there is no explicit standard or spec about that.

So, IMO it is better not to use `minimatch` and `gitignore` simultaneously unless we have to. Or, at least, maybe `gitignore` rules should comes first, then `minimatch`.

**Comment by kaelzhang** [comment]
Maybe we'd move this topic to sindresorhus/globby#50

**Comment by kaelzhang** [comment]
Close for now
